name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Ou a branch que você está usando para desenvolvimento

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ou a versão do Node que você está usando

      - name: Install dependencies
        run: npm install

      - name: Set up secrets
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}  # Exemplo de como passar secrets como variáveis de ambiente

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
